### ISSUE TITLE
2024 Q4 Discovery & Research: Debt Services: Financial Management Experience information gathering

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#101]
### User Story
As the UX researcher on the MFS team, 
I need to understand the Financial Management Experience products,
So that we can better understand the current state of debt services.

### Additional Info and Resources
The Financial Management Experience products are currently being migrated to a new API by the Lighthouse team.
We need to better understand the Debt Services objective, and how it will fit into the Bluesky design vision, then outline the outstanding UX and research work that needs to be done. 

Denise Coveyduck ([denise.coveyduc@va.gov](mailto:denise.coveyduc@va.gov)) is the PO for this effort and is willing to discuss this with research resouces. 

## Tasks
- [ ] Explore team and product structure for previous + current debt work
- [ ] Write summary of debt services product structure
- [ ] Meet with Denise Coveyduck after the Bluesky design vision presentation to document the current experience within Debt Services
- [ ] Outline current user experience based on meeting with Denise
- [ ] Capture any **future user experience requirements** from VA/Denise

## Acceptance Criteria
- [ ] There is an understanding of the Debt Services work as current state
- [ ] There is documentation of the desired future user experience from VA/Denise
- [ ] Future work is outlined
