### ISSUE TITLE
2024 Q4 Pre-Need Burial Claim: Perigean coordination

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#103]
### User Story
As the UX and Research teams on MFS, 
We need to request and meet with Perigean,
So that we can continue validating the research and assumptions established by the Flagship Mobile team concerning Pre-Needs Burial Claims prior to implementation on the Mobile App.

### Overview
Currently eligible Veterans engaging with the VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) do not have a way to find, track and get statuses in the VA Flagship App. This means the Veterans can only go through Va.gov to access this information.

In June 2017, VA launched VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) on Vets.gov. Vets.gov later transitioned to Va.Gov which currently enables Veterans to discover, apply for, track and manage this claim.

As of today, current focus has only been on maintaining this feature. 

Pre-need decision letter is not needed for a service member that is on active duty.

Pre-Need Burial Claims are not currently in the claims status tool, only burial claims are in the claims too.

Specifically, we need to understand if the work outlined by Flagship Mobile back in 2023 is still viable and the most effective and efficient way to proceed.

## Tasks
- [ ] Write questions specifically for Perigean - reference [successful screener questions](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions)
- [ ] Create a [recruitment request ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new?assignees=sstrassberg&labels=recruitment-criteria&template=recruitment+criteria.yaml&title=%5BRecruitment+Request%5D%3A+YYYY-MM+name+of+your+study)
- [ ] Request a kick-off call with Perigean
- [ ] Create agenda for Perigean meeting
- [ ] Meet with Perigean about the research assumptions

## Acceptance Criteria
- [ ] Understanding of the research, having it validated by Perigean
