### ISSUE TITLE
2024 Q4 Pre-Need Burial Claims: Creating Recruiter screener for future research candidates

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#104]
### User Story
As the UX and Research teams on MFS, 
We need to prepare for screener research,
So that when there are screening opportunities, they are treated consistently.

### Overview
Currently eligible Veterans engaging with the VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) do not have a way to find, track and get statuses in the VA Flagship App. This means the Veterans can only go through Va.gov to access this information.

In June 2017, VA launched VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) on Vets.gov. Vets.gov later transitioned to Va.Gov which currently enables Veterans to discover, apply for, track and manage this claim.

As of today, current focus has only been on maintaining this feature. 

Pre-need decision letter is not needed for a service member that is on active duty.

Pre-Need Burial Claims are not currently in the claims status tool, only burial claims are in the claims too.

Specifically, we need to understand if the work outlined by Flagship Mobile back in 2023 is still viable and the most effective and efficient way to proceed.

## Tasks
- [ ] Review the current research from Flagship Mobile [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/burials-memorials/pre-need/research)
- [ ] Create conversation guide
- [ ] Submit for review

## Acceptance Criteria
- [ ] Flagship Mobile research has been validated, and the outstanding work can be ticketed for future Sprints.
