### ISSUE TITLE
Discovery: API shadowing

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#108]
### User Story
As the Backend engineers on the MFS team, 
We need to shadow other API development teams,
So that familiarity with the code is established prior to deadline-driven work schedules.

### Overview
It would benefit our BE engineer to do some shadowing of the teams currently working on the APIs to further familiarize the dev with the code. 

## Tasks
- [ ] Contact Platform Tech Lead to schedule shadow time
- [ ] Contact Lighthouse Tech Lead to schedule shadow time
- [ ] Create documentation that records findings and API work covered in those shadow opportunities

## Acceptance Criteria
- [ ] Shadowing is complete
- [ ] Documentation with findings and the API work covered during shadowing events
