### ISSUE TITLE
2024 Q4 MFS: Accessibility Tools / UX

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#114]
### User Story
As the UX and Research resources for the VA MFS team, 
We need to document and understand the current Accessibility tools,
So that all future work for the MFS team is created in alignment with Accessibility requirements.

### Background
For this ticket, UX needs to review the current Accessibility tools (found [here](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Accessibility/testing-plan/); scroll down to **Section 2: Test Environment**; **Test Tools**). These are the tools listed by the Flagship Mobile team as what they use for Accessibility checks. 
- Voiceover (iOS) and Talkback (Android) will be used to test Screen Reader capabilities
- Bluetooth keyboards* will be used to test keyboard operability.
- The type of bluetooth keyboard will be confirmed once devices are procured.
- Deque mobile app testing for iOS and Android may be used to audit the app as a comprehensive set of functionality is developed.

Goal is to do a deep dive into the current a11y requirements from Flagship and to make recommendations on what could be embellished.

## Tasks
- [ ] Review and document the Accessibility tools currently in use by the Flagship Mobile team
- [ ] Determine if there are better options
- [ ] Obtain Accessibility testing tools as necessary
- [ ] Document the Accessibility tools and how they should be used, from the engineering POV.

## Acceptance Criteria
- [ ] UX on the MFS team have a better idea of the Accessibility testing process
- [ ] Documentation as required
