### ISSUE TITLE
2024 Q4 MFS Pre-Need Burial: API work

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#116]
### User Story
As the Back End Engineers on the MFS team, 
We need to identify and update the Pre-Need Burial API owners,
So that future planning can be completed based on what work has been validated.

### Overview
Currently eligible Veterans engaging with the VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) do not have a way to find, track and get statuses in the VA Flagship App. This means the Veterans can only go through Va.gov to access this information.

In June 2017, VA launched VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) on Vets.gov. Vets.gov later transitioned to Va.Gov which currently enables Veterans to discover, apply for, track and manage this claim.

As of today, current focus has only been on maintaining this feature. 

Pre-need decision letter is not needed for a service member that is on active duty.

Pre-Need Burial Claims are not currently in the claims status tool, only burial claims are in the claims too.

Specifically, we need to understand if the work outlined by Flagship Mobile back in 2023 is still viable and the most effective and efficient way to proceed.

**Outputs from the Eng Spike ticket (82):** 
The API has an implementation that essentially mirrors what goes on in the standard pre need burial controllers for va.gov

- [Mobile Controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/app/controllers/mobile/v0/pre_need_burial_controller.rb)
- [va.gov controller](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/preneeds/burial_forms_controller.rb)

The mobile controller doesn't really do anything with confirmation emails or anything like that so there are some slight differences. In OCTO Slack, Kenny Santiago (from one of the main vets-api teams) and Andrew Herzberg (a dev from the flagship team) where Santiago says they had just picked up the API as part of their portfolio and they needed to do some research to see if there were additional options that we were currently exposing via the API.

![Image](https://github.com/user-attachments/assets/5b72684c-e18f-4d7b-963f-90e2ea0db444)

We need to follow up with whatever team currently owns that API and figure out if the proposed research was ever done and/or if it could be. When the code for the va.gov controller was reviewed, it didn't appear that much has changed significantly since then, so the answers could be: "We haven't done that research", or "We did it and there isn't a downstream API to support status checks".

## Tasks
- [ ] Determine API (if there is one currently)
- [ ] Determine owner of this API
- [ ] Confirm if the research was completed
- [ ] Review research
- [ ] Identify any possible deltas
- [ ] Ticket that new work
- [ ] Document findings

## Acceptance Criteria
- [ ] API research is verified _or_
- [ ] Research is confirmed to not be complete
- [ ] Create tickets for any new work
- [ ] Documentation of process is complete
