### ISSUE TITLE
Pre- Needs Burial: Submit Collab Cycle kickoff request

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#123]
### User Story
As the UX team on the MFS team, 
We need to be involved with the Governance team's Collaboration Cycle for new product development and request a Collab Cycle kickoff request,
So that our development is being done in-line with Governance and VA requirements.

### Overview
When we are in process with the Pre-Need Burial Development, we need to follow this guidance by the Governance team to be in sync with the Collaboration Cycle. The Collaboration Cycle kickoff is the first touchpoint in the Collaboration Cycle.

The kickoff is not a synchronous meeting; rather, it is a request that initiates the Collaboration Cycle process via a GitHub ticket. This ticket will be the primary source of truth for both the Governance Team and the Sitewide Content, Accessibility, and Information Architecture (CAIA) team throughout your team’s Collaboration Cycle process.

**Kickoff steps**
Your Product Manager or another representative from your team [submits a Collaboration Cycle Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D), answering the kickoff questions.

Within a business day, the Governance Team updates the ticket with recommended touchpoints for your team and notifies the team on Slack.

Once the kickoff request has been acknowledged and completed, you are ready to move to the next touchpoint, usually the [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/design-intent). CAIA may also reach out to you to assess your needs for collaboration on content, IA, and accessibility.

**Completing the kickoff request ticket**
Review our [terms and definitions regarding products vs. features](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-term-glossary). This information needs to be included in the Kickoff request: 
1. Will your work result in visible changes to the user experience?
- Examples of visible changes include:
- Any changes that the user will see
- Adding a new form, tool, or page
- Modifying buttons, design elements, interactions, or page layouts
- Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages
- Examples of no visible changes include:
- Changes to code that the user won’t see
- Changes to accessible labels (aria-label, aria-labelledby, aria-describedby)

2. Are you doing research with VA.gov users? _We ask this question to determine if a research review is necessary_.
Examples of research with VA.gov users include:
- Usability testing
- User surveys
- Card sorting

3. Will your work involve changes to: (select all that apply)
- [ ] Tools, applications and dynamic pages*
- [ ] Static pages**
- [ ] Both
- [ ] Other
*For tools and applications, take into account if any static page entry points will need updates.
**Please review the [Static vs Dynamic](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md) guidance.

4. Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?
We ask this question to determine if Analytics will need to be involved in your Collaboration Cycle reviews, and if an Analytics Request is necessary.

5. Do you need to capture any additional analytics or metrics?
We ask this question to determine if Analytics will need to be involved in your Collaboration Cycle reviews, and if an Analytics Request is necessary.

6. Will a VA editor (Drupal) notice this change?
A VA editor creates content that informs the public about VA facilities - operating hours, services offered at specific locations - or else public content that describes benefits and procedures for applying for them. We ask this question to determine if a CMS Request is necessary.

7. Link to artifacts
It is the Product Manager’s responsibility to ensure the link to the [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md) is added to the ticket. The VFS team is responsible for providing all relevant and up-to-date links, screenshots, images, and designs of the product's as-is version.

## Tasks
- [ ] Create outline of the kickoff ticket for product
- [ ] Complete outline of the kickoff ticket for the product
- [ ] Submit completed kickoff ticket to Governance team for review

## Acceptance Criteria
- [ ] We have received feedback from the Governance team on how to best proceed

## QA Considerations
- Will need to have user stories for Pre-Need Burial Service Claim written at this time

## Potential Dependencies
- Turn-around time from Governance team to do this review.

## Out of Scope
- Implementing new product is out of scope for this ticket, this ticket is just to submit the Kickoff request to the Governance team
