### ISSUE TITLE
Pre-Need Burial: Collab Cycle Design Intent

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#125]
### User Story
As the UX team on the MFS team, 
We have completed a user flow and wireframe for Design Intent review,
So that we can hold the Design Intent review meeting and get approval(s) on the user flow and wireframe proposal.

### Overview
When we are ready with a user flow and wireframes for the proposed design of Pre-Needs Burial Development, we need to follow this guidance by the Governance team to be in sync with the Collaboration Cycle. The Design Intent is the third touchpoint in the Collaboration Cycle.

What’s the purpose of the Design Intent?
The goal of the Design Intent meeting (or “touchpoint”) is to ensure you’re building a product that meets VA.gov standards before you’ve done any high-fidelity work on artifacts or prototypes.

This meeting is less a formal presentation and more a discussion. It not only provides OCTO-DE and Platform with an early understanding of the product/feature your team wants to build, but is also an opportunity to collaborate and provide feedback on the user experience, your product’s overall design, and on any adjustments needed to meet [VA.gov experience standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards). The focus is on making sure the flow makes sense for the user given your constraints.

For an overview of the Design Intent process, please see [this video](https://youtu.be/v1TkKqOpDuo).

Preparing for the Design Intent: _When should the Design Intent be scheduled_?
Schedule this meeting when:
- An idea for how to solve your problem statement has been developed
- A user workflow has been drafted
- A lo-fi prototype and/or wireframe has been drafted

Note: The Governance Team will need at least 2 business days to review your materials. Ensure you provide enough lead time, otherwise the meeting may need to be rescheduled.

What artifacts will be needed?
Artifacts are anything that will help the Governance Team and OCTO-DE understand your product, e.g. wireframes, user flows, etc.

Clearly define and communicate the scope of your product. Is this an entirely new product? Is only one part of a form being updated? Are there any specific areas that the Governance team reviews should focus on? 

Artifacts should be ready and linked in the VFS team’s Collaboration Cycle Request GitHub ticket at least **2 business days** before the scheduled meeting.

**Required artifact**
User flow. One of the most important functions of this meeting is understanding your intended user experience. We’re looking for a visual representation of the interaction points and decisions your user will encounter. This user flow doesn’t need to be high-fidelity; a simple flowchart of arrows and shapes is acceptable.

[Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)

For help with user flows, reach out to the CAIA IA team through the #sitewide-content-accessibility-ia channel on Slack.

**Nice to have:** 
- Wireframes. The Governance Team and OCTO-DE aren’t looking for high fidelity at this point, so don’t worry about them being polished. But if you’re providing wireframes, [design mobile-first](https://design.va.gov/about/principles#usable-by-everyone) and provide wireframes for mobile devices rather than just a full desktop display.
- Research plan
- Any other relevant artifacts you may want to share

How to schedule the Design Intent
- [ ] Follow the steps in the Collaboration Cycle Request GitHub ticket.
- [ ] Schedule: Use the Calendly link in the Before Meeting > VFS Actions section to select a date for the touchpoint meeting. The Governance Team will reach out within a business day via Slack to confirm the scheduling of the touchpoint.
- [ ] Add artifacts: Go to the Before meeting > Design Intent artifacts checklist and make sure the requested artifacts are linked.
- [ ] Please request the Design Intent meeting and provide artifacts at least 2 business days ahead of time so the Governance Team can review provided artifacts.

Who should schedule the Design Intent?
No one specific role on the VFS team is required to schedule the Design Intent. However, whoever schedules the Design Intent and notifies the Governance Team through Slack will be responsible for inviting the rest of their team to the scheduled Design Intent meeting.

Who should attend the Design Intent?
The VFS team’s designer(s) and product manager should attend the Design Intent. You’re also encouraged to invite relevant members of your team, such as content, IA, accessibility, QA specialists, and VA stakeholders who will be working on or advising the product.

The Governance team will ensure that the relevant Platform and OCTO-DE participants are invited.

What happens during the Design Intent?
- 30-minute synchronous Zoom meeting
- Hosted by the Governance Team
- Recorded for later reference

Agenda (_Design Intent meetings often follow this format_):
- The Governance Team welcomes everyone to the call.
- Your team has about 10 minutes to introduce your initiative. We recommend using this time to:
- Discuss the problem space you are trying to solve for, including any constraints you’re facing.
- Present your artifacts and walk us through the user flow.
- OCTO-DE and the Governance Team will ask questions and provide feedback. (They'll also provide you with written feedback through Github after the meeting).

What sort of feedback can teams expect?
After you present your artifacts and explain the user flow, OCTO-DE and the Governance Team will ask questions and provide feedback. They may:
- Recommend applicable Design System components and/or patterns
- Share relevant insights or flows from other VA.gov work
- Recommend changes to the user flow or page structure to meet Accessibility and IA standards.

Remember, this is more of a discussion than a formal presentation. If you have questions you want answered or have questions about the feedback, ask!

After the Design Intent Meeting
After the meeting, the Governance Team will add the link to the recording of the meeting to the Collaboration Cycle Request GitHub ticket.

Governance team design, accessibility, and IA reviewers will document their feedback with GitHub tickets following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Feedback tickets will be linked to the Collaboration Cycle Request GitHub ticket and can be found through the associated Milestone. Feedback tickets will be available no later than the end of the next business day following the meeting.

Once the Feedback is provided, you can update your plan & design to conform to relevant Platform standards.

## Tasks
- [ ] Schedule: Use the Calendly link in the Before Meeting > VFS Actions section to select a date for the touchpoint meeting. The Governance Team will reach out within a business day via Slack to confirm the scheduling of the touchpoint.
- [ ] Add artifacts: Go to the Before meeting > Design Intent artifacts checklist and make sure the requested artifacts are linked to the Collab Cycle ticket
- [ ] Please request the Design Intent meeting (provide artifacts 2 days in advance of the meeting for review)

## Acceptance Criteria
- [ ] Design Intent meeting held and notes are taken 
- [ ] We have received feedback on the proposed plan and have ticketed any work to adjust the plan and design to conform to relevant standards. 

## Potential Dependencies
- Turn-around time from Governance team to review (2 business days are the standard)

## Out of Scope
- Implementing new product is out of scope for this ticket, this ticket is just to hold the Pre-Needs Burial Design Intent meeting
