### ISSUE TITLE
2024 Veterans Status Card: Collab Cycle Architecture Intent

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#140]
### User Story
As the UX team on the MFS team, 
We are ready to discuss our technical approach for the Pre-Needs Burial objective,
So we are requesting Support by the Governance team to schedule an Architecture intent meeting.

### Overview
When the MFS team is ready to discuss the Architecture intent for the Veterans Status Card objective, we need to follow this guidance by the Governance team to be in sync with the Collaboration Cycle. The Architecture Intent is the fourth touchpoint in the Collaboration Cycle.

What’s the purpose of the Architecture Intent?
The goal of the Architecture Intent meeting (or “touchpoint”) is to ensure you’re building a product that meets VA.gov Engineering and Security standards before you’ve started building your product.

This meeting is less a formal presentation and more a collaborative discussion surrounding the architectural decisions that impact the engineering and security posture of the product you are building or iterating on. It not only provides OCTO-DE and Platform with an early understanding of the product/feature your team wants to build, but is also an opportunity to collaborate with VA’s engineering and security stakeholders to assist you with building out the correct technical solution. The focus is on making sure your code meets user needs within the constraints of the platform you're building on.

Preparing for the Architecture Intent - _When should the Architecture Intent be scheduled_?
The Architecture Intent meeting should be scheduled if any of these apply and we are at a point where MFS is  ready to discuss our approach to Pre-Needs Burial:
- There are questions about one or more points on the [template below](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/architecture-intent#What-artifacts-will-be-needed%3F).
- There are issues locating or getting technical info from other stakeholders or system owners.
- The product in development will launch a new service or major new feature.
- The MFS team is using an architecture pattern not currently found on the VA.gov Platform.
- The MFS team plans to use a new technology, library or dependency.
- The product will integrate with a new system or API, inside or outside of the VA.
- The change(s) requires complex coordination across teams or you need support to coordinate across teams.
- New Personally Identifiable Information ([PII](https://en.wikipedia.org/wiki/Personal_data)) and/or Protected Health Information ([PHI](https://en.wikipedia.org/wiki/Protected_health_information)) is being gathered or saving PII/PHI in a new place.
- There are cost, performance or security implications to your change.

Note: OCTO-DE will need at least 2 business days to review your materials. Ensure that enough lead time is alloted, otherwise the meeting may need to be rescheduled.

What artifacts will be needed? _Artifacts are anything that will help OCTO-DE understand the proposed product. There are 2 required artifacts_:
- [ ] Please fully fill out the [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md) and store the Architecture Diagrams in the [Diagrams folder in the Sensitive Repo](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/platform/engineering/collaboration-cycle/architecture-intent/diagrams).
- [ ] Create a [user data flow diagram](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/practices/zero-silent-failures/how-to-create-a-user-data-flow-diagram.md) if the  application accepts data from a user.

The artifacts should be ready and linked in the VFS team’s Collaboration Cycle Request GitHub ticket at least 2 business days before the scheduled meeting.

Follow the steps in your team’s Collaboration Cycle Request GitHub ticket to schedule the Architecture Intent

Schedule: Use the Calendly link in the Before Meeting > VFS Actions section to select a date for the touchpoint meeting. The Governance Team will reach out within a business day via Slack to confirm that your touchpoint has been scheduled.

Add artifacts: Using the [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md), make sure clear answers have been added to every section on the ticket.

Please request your Architecture Intent meeting and provide artifacts at least 2 business days ahead of time so the Governance Team can review your artifacts.

Who should schedule the Architecture Intent?
- No one specific role on the VFS team is required to schedule the Architecture Intent. However, whoever schedules the Architecture Intent and notifies the Governance Team through Slack will be responsible for inviting the rest of their team to the scheduled Architecture Intent meeting.

Who should attend the Architecture Intent?
- The VFS team’s technical leadership and product manager should attend the Architecture Intent. You’re also encouraged to invite relevant members of your team, such as engineers, and VA stakeholders who will be working on or advising the product.

The Governance team will ensure that the relevant Platform and OCTO-DE participants are invited.

What happens during the Architecture Intent?
- 30-minute synchronous Zoom meeting
- Hosted by OCTO-DE
- Recorded for later reference

Agenda
Architecture Intent meetings often follow this format:
- OCTO-DE welcomes everyone to the call.
- Your team has about 10 minutes to introduce your initiative. We recommend using this time to:
- Discuss the problem space you are trying to solve for, including any constraints you’re facing.
- Present your artifacts and walk us through the technical direction
- OCTO-DE will ask questions and provide feedback. They'll also provide you with written feedback through GitHub after the meeting.

What sort of feedback can teams expect?
After you present your artifacts and explain the user flow, OCTO-DE will ask questions and provide feedback. They may:
- Share what other teams have done in the past to solve this technical problem
- Share information about security rules and/or implications based on your given approach

Remember, this is more of a discussion than a formal presentation. If you have questions you want answered or have questions about the feedback, ask!

After the Architecture Intent Meeting
After the meeting, OCTO-DE will add the link to the recording of the meeting to the Collaboration Cycle Request GitHub ticket.

OCTO-DE Engineering and Security stakeholders will document their feedback with GitHub Project tickets. Once the Feedback is provided, the technical plan can be updated to conform to relevant Engineering and Security standards.

## Tasks
- [ ] Schedule: Use the Calendly link in the Before Meeting > VFS Actions section to select a date for the touchpoint meeting. The Governance Team will reach out within a business day via Slack to confirm that your touchpoint has been scheduled.
- [ ] Add artifacts: Using the [Architecture Intent Meeting Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/collab-cycle/architecture-intent-meeting.md), make sure clear answers have been added to every section on the ticket.
- [ ] Please request the Architectural Intent meeting (provide artifacts at lease 2 days in advance of the meeting for review)

## Acceptance Criteria
- [ ] Architecture Intent meeting held and notes are taken 
- [ ] We have received feedback on the proposed plan and have ticketed any work to adjust the plan and design to conform to relevant standards. 

## Potential Dependencies
- Turn-around time from Governance team to review (2 business days are the minimum standard)

## Out of Scope
- Implementing new product is out of scope for this ticket, this ticket is just to hold the Veterans Status Card Architectural Intent meeting
