### ISSUE TITLE
2024 Veterans Status Card: Collab Cycle Midpoint Review

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#141]
### User Story
As the UX team on the MFS team, 
We have a high-fidelity design and are preparing to do research on Veterans Status Card, 
So we are requesting the Governance team to schedule a Midpoint Review on our objective.

### Overview
What's the purpose of Midpoint Review?
The goal of the Midpoint Review touchpoint is to ensure that the new product aligns with VA.gov standards as  designs are finalized. This touchpoint should be scheduled when a team has a prototype or mockup ready to put in front of users for research.

Preparing for the Midpoint Review
The meeting can be either asynchronous or synchronous, and can be scheduled a Midpoint Review in either of these formats:
- Synchronous: Live, 30-minute Zoom meeting with Governance team, or
- Asynchronous: Review is scheduled, but no meeting is held. Governance team members review your research and design artifacts on their own, and append their feedback to your request ticket.

Governance recommends a synchronous meeting if this is the first time you’re introducing Platform to your product, or if there have been significant changes since your Design Intent. Note: If you choose an asynchronous review and the Governance team decides your product requires a more in-depth consultation, we may change the review format to synchronous. If that happens, we will let you know ahead of time.

When should the Midpoint Review be scheduled? Schedule this touchpoint when:
- There is a high-fidelity design or prototype
- The MFS team is preparing to do user research
- Synchronous and asynchronous reviews are scheduled using the same process. Follow the instructions in the Collaboration Cycle ticket to schedule.

The Governance Team will need at least 2 business days to review your materials. Ensure you provide enough lead time, otherwise the meeting may need to be rescheduled.

What artifacts will be needed? _Artifacts are anything that will help the Governance Team and OCTO-DE understand your product, e.g. wireframes, user flows, etc._
The following artifacts should be ready and linked in the VFS team’s Collaboration Cycle Request GitHub ticket at least 2 business days before the scheduled meeting.
- Design prototype or high-fidelity mockup. If a design is not yet available, consider scheduling a Design Intent instead.
- A version of your prototype or mockup sized for mobile devices must be supplied
- Versions for larger devices (eg. desktop) are encouraged. 
- Up to date user flow. A user flow doesn’t need to be high-fidelity; a simple flowchart of arrows and shapes is acceptable. If there have been big changes since Design Intent, ensure the flow is up to date. If the Design Intent meeting, Governance will ask to discuss the user flow at your Midpoint Review.

[Guidance on user flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)

For help with user flows, reach out to the CAIA IA team through the #sitewide-content-accessibility-ia channel on Slack.

If working with CAIA, link to CAIA intake ticket. The Governance Team needs this information to understand whether and how you’ve been getting assistance from the [Sitewide Content, Accessibility and Information Architecture team](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request).

Not required, but nice to have artifacts
- [Accessibility annotations](https://design.va.gov/about/accessibility/accessibility-annotations) included as part of the design
- Research plan
- Links to specific CAIA artifacts:
- IA spec
- Content source of truth
- Any other artifacts you have so far

How to schedule a Midpoint Review
Follow the steps in the Collaboration Cycle Request GitHub ticket.

Schedule: Use the Calendly link in the Before Meeting > VFS Actions section to select a date for the touchpoint meeting. The Governance Team will reach out within a business day via Slack to confirm that your touchpoint has been scheduled.

Add artifacts: Go to the Before meeting > Midpoint Review artifacts checklist and make sure the requested artifacts are linked.

Please request your Midpoint Review meeting and provide artifacts at least 2 business days ahead of time so the Governance Team can review your artifacts.

Who should schedule the Midpoint Review?
No one specific role on the VFS team is required to schedule the Midpoint Review. However, whoever schedules the Midpoint Review in Calendly will be responsible for inviting the rest of their team to the scheduled Midpoint Review meeting.

Who should attend the Midpoint Review?
The VFS team’s designer(s) and product manager should attend the Midpoint Review. You’re also encouraged to invite relevant members of your team, such as content, IA, accessibility, QA specialists, and VA stakeholders who will be working on or advising the product.

The Governance team will ensure that the relevant Platform and OCTO-DE participants are invited.

What happens during the Midpoint Review?
- 30-minute synchronous Zoom meeting
- Hosted by the Governance Team
- Recorded for later reference

Agenda
Midpoint Review meetings often follow this format:
- The Governance Team welcomes everyone to the call.
- Teams have 5 minutes to provide an update on what’s changed since Design Intent. _If_ MFS did not have a Design Intent meeting, there will be 10 minutes to introduce the initiative. It is recommended to use this time to:
- Discuss the problem space you are trying to solve for, including any constraints you’re facing.
- Present your artifacts and ask for specific areas where you’d like feedback.
- The Governance Team and OCTO-DE practice area leads will ask questions and provide feedback. They'll also provide you with written feedback through Github after the meeting.

What sort of feedback can teams expect?
After you present your artifacts, OCTO-DE and the Governance Team will ask questions and provide feedback. They may:
- Recommend applicable Design System components and/or patterns
- Share relevant insights or flows from other VA.gov work
- Recommend changes to the user flow or page structure to meet Accessibility and IA standards.
- Make suggestions for your research plan.

After the Midpoint Review meeting
- After the meeting, the Governance Team will add the link to the recording of the meeting to the Collaboration Cycle Request GitHub ticket.
- Governance team design, accessibility, content, and IA reviewers will document their feedback with GitHub tickets following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Feedback tickets will be linked to the Collaboration Cycle Request GitHub ticket and can be found through the associated Milestone. Feedback tickets will be available no later than the end of the next business day following the meeting.
- Once the Feedback is provided, you can update your plan & design to conform to relevant Platform standards. You can then move on to the next design touchpoint: the [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review).

## Tasks
- [ ] Schedule: Use the Calendly link in the Before Meeting > VFS Actions section to select a date for the touchpoint meeting. The Governance Team will reach out within a business day via Slack to confirm that your touchpoint has been scheduled.
- [ ] Add artifacts: Go to the Before meeting > Midpoint Review artifacts checklist and make sure the requested artifacts are linked.
- [ ] Please request the MidPoint Review meeting (provide artifacts at lease 2 days in advance of the meeting for review)

## Acceptance Criteria
- [ ] Midpoint Review meeting held and notes are taken 
- [ ] We have received feedback on the proposed plan and have ticketed any work to adjust the plan and design to conform to relevant standards. 

## Potential Dependencies
- Turn-around time from Governance team to review (2 business days are the minimum standard)

## Out of Scope
- Implementing new product is out of scope for this ticket, this ticket is just to hold the Veterans Status Card Midpoint Review meeting
