### ISSUE TITLE
VA Mobile Onboarding - Access to Mural for MFS team

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#36]
### User Story
As the UX Researcher for VA MFS, 
We need to have access to the Mural tool, 
So that we can do UX and other planning for the work.

### Description
Our team needs access to Mural so that we can plan our work in a visual and strategic manner.

### Tasks
- [x] Need to determine how to get access to Mural for the team - are there adequate licenses available?
- [x] Get access for @nhuckleberry6 @oddballpete @Eallan919 @ATeal @oddballdave, @jennb33 @emilyd-oddball 

### Acceptance Criteria
- [x] Our team has access to Mural to create and use for planning
