### ISSUE TITLE
MFS Comparison: Web Backend current state review: Eng analysis

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#38]
### User Story
As the developers and managers of MFS, 
We need to crosswalk the current state of the Backend of [VA.gov](https://www.va.gov/) website product to the VA Mobile Flagship product, 
So that our team is informed on the current state of the two tools, and can understand what product development would be most beneficial to our planning. 

### Description
We are going to compare the backend of the current VA.gov environment and try to identify opportunities for new product development. This will also assist in creating a list of possible objectives that are low-hanging fruit for our team to create and produce. Goal is to identify opportunities where two different support systems - is there a singular backend that can service the App? 
Some questions to consider: 
- What was the point that Mobile decided that they need their own APIs? 
- Currently all APIs are tailored to Mobile's spec.
- IIR had some dynamic error messages; Mobile scaled theirs back. 

### Tasks
- [ ] Review and document current state of [VA.gov](https://www.va.gov/) products/services from the Engineering perspective
- [ ] Share documentation of findings internally for review and prioritization with PgM, Product Lead, and PM
- [ ] Link documentation of findings in this ticket's comment section

### Acceptance Criteria
- [ ] We have documentation from the Engineering analysis perspective on VA.gov
- [ ] We are able to leverage the findings
- [ ] Findings are documented

### Additional Info and Resources
Items to focus on: 
- [ ] General understanding of VA.gov, services and products
- [ ] General understanding of the basic channels on VA.gov
