### ISSUE TITLE
MFS Comparison: App current state: Eng analysis

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#41]
### User Story
As the designers, developers and managers of MFS, 
We need to perform analysis on the current state of the MVP Flagship Mobile product, 
So that our team is informed on the current state of the tool, and can understand what product development would be most beneficial to our planning. 

### Description
We are going to compare the tools and services currently available on the MVP Flagship Mobile app and create a list of areas where product development to benefit the end users would be high priority, which will allow for better product that we produce. This will also assist in creating a list of possible objectives that are low-hanging fruit for our team to create and produce. 

### Tasks
- [ ] Review and document current state of MVP Flagship Mobile products/services from the Engineering perspective
- [ ] Share documentation of findings internally for review and prioritization with PgM, Product Lead, and PM
- [ ] Link documentation of findings in this ticket's comment section

### Acceptance Criteria
- [ ] We have documentation from the Engineering analysis perspective on MVP Flagship Mobile
- [ ] We are able to leverage the findings
- [ ] Findings are documented
