### ISSUE TITLE
MFS Comparison: Crosswalk outputs from comparison/analysis of web and Flagship Mobile products

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#42]
### User Story
As the developers and managers of MFS, 
We need to crosswalk the current state of the [VA.gov](https://www.va.gov/) website product to the VA Mobile Flagship product, 
So that our team is informed on the current state of the two tools, and can understand what product development would be most beneficial to our planning. 

### Description
We are going to compare the tools and services currently available for VA.gov and create a list of areas where product development to benefit the end users would be high priority, which will allow for better product that we produce. This will also assist in creating a list of possible objectives that are low-hanging fruit for our team to create and produce. 

### Tasks
- [ ] Review outputs from these tickets: [38](https://github.com/department-of-veterans-affairs/va-mobile-feature-support/issues/38), [39](https://github.com/department-of-veterans-affairs/va-mobile-feature-support/issues/39), [40](https://github.com/department-of-veterans-affairs/va-mobile-feature-support/issues/40), [41](https://github.com/department-of-veterans-affairs/va-mobile-feature-support/issues/41) 
- [ ] Compare findings and document opportunities
- [ ] Share documentation of findings internally for review and prioritization with PgM, Product Lead, and PM
- [ ] Link documentation of findings in this ticket's comment section

### Acceptance Criteria
- [ ] We have a crosswalk of VA.gov and the VA Flagship Mobile products/services
- [ ] We are able to leverage the findings
- [ ] Findings are documented
