### ISSUE TITLE
Updating App Unit Tests to use i18n Translations - Home (5)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#53]
This ticket is taken from the Flagship Mobile team board, [ticket #9997](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9997)

## Proposed Change

Update the following tests to use the i18n translations instead of hardcoded strings:

- VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/AccountSecurity/AccountSecurity.test.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.test.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/NotificationsSettingsScreen/NotificationsSettingsScreen.test.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.test.tsx

## Why Should We Prioritize?

This will make our unit tests less brittle while remaining vigilant in our coding defense.

## Tasks
- [ ] Perform unit test as described in "Proposed Changes"
- [ ] Share merge request link in comments below

## Definition of done
Team will be comfortable working in the existing code and will be better able to build and troubleshoot issues that come up.

## Acceptance Criteria
- [ ] Test for i18n Translations is complete
