### ISSUE TITLE
Updating App Unit Tests to use i18n Translations - Login

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#58]
This ticket is taken from the Flagship Mobile team board, [ticket #9989](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9989)

## High Level User Story/ies
As a the Developers and Engineers of the MFS team,  
We need to run unit tests on the current code,
so that we are familiar with the code and will be better prepared to troubleshoot the issues and errors in the current Mobile MVP space.

## Proposed Change

Update the following tests to use the i18n translations instead of hardcoded strings:
- VAMobile/src/screens/auth/LoaGate/LoaGate.test.tsx
- VAMobile/src/screens/auth/LoginScreen/LoginScreen.test.tsx
- VAMobile/src/screens/OnboardingCarousel/OnboardingCarousel.test.tsx
- VAMobile/src/screens/SyncScreen/SyncScreen.test.tsx
- VAMobile/src/screens/auth/LoginScreen/LoginScreen.test.tsx

## Why Should We Prioritize?

This will make our unit tests less brittle while remaining vigilant in our coding defense.

## Tasks
- [ ] Perform unit test as described in "Proposed Changes"
- [ ] Share merge request link in comments below

## Definition of done
Team will be comfortable working in the existing code and will be better able to build and troubleshoot issues that come up.

## Acceptance Criteria
- [ ] Test for i18n Translations is complete
