### ISSUE TITLE
UX review of current environment

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#59]
## High Level User Story/ies
As a UX Researcher on the MFS team, 
We need to walk through the current mobile system with the UX Lead,
so that there is a better understanding of the OCTO VAPO vision for the UX work.

## Tasks
- [x] Attend meeting on Wednesday, 11/6, to review the current Mobile interface 
- [x] Discuss prioritization of the work with OCTO VAPO
- [x] Discuss ownership of the work with OCTO VAPO
- [ ] Document decisions

## Acceptance Criteria
We have a more clearly defined idea of the expectations from OCTO VAPO and a better sense of the prioritization of the needs of VAPO. 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*
