### ISSUE TITLE
Create Product Charter

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#62]
## High Level User Story/ies
As the Product Manager for the MFS Product, 
We need to create a Product Charter for MFS,
so that the work, objectives, and product scope are clearly defined and agreed upon by all stakeholders. 

## Description
Having a Mission Statement and a Product Charter will help to solidify the goals, scope, and desired outcomes for the team. This ticket is to cover the work necessary to create the Product Charter.

## Tasks
- [ ] Draft Product Charter
- [ ] Circulate draft for feedback
- [ ] Make edits based on feedback
- [ ] Finalize Product Charter and circulate it to team
- [ ] Document where Product Charter can be found and share with stakeholders

## Desired Outcomes
We will have an approved Product Charter that will be leveraged by the team. 

## Acceptance Criteria
We will have an approved Product Charter that will be leveraged in other team documents and by the team.
