### ISSUE TITLE
Create Data Dictionary for MFS team

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#66]
### User Story
As the MFS team, 
We need to create a data dictionary for our program, or leverage one from IIR, 
so that all acronyms are understood and there is a central repository for reference.

### Overview
We need to create a Data Dictionary in GitHub for all team stakeholders and resources to refer to when encountering an unknown acronym or phrase that are common when working on VA tasks.

## Tasks
- [ ] Create GitHub space for Data Dictionary, if one does not already exist
- [ ] Update as necessary (this will be a live document)
- [ ] Share with all team resources how to find the Data Dictionary.

## Acceptance Criteria
- [ ] Once the initial space has been set up and shared with stakeholders and the team, this ticket can be closed.
