### ISSUE TITLE
Discovery - Review Reddit and find feedback that will help build future sprint work

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#67]
### User Story
As the Product and UX resources on the MFS team,
We need to review the Reddit application specific to comments about the Mobile App, 
so that we know how to plan our strategies, further research, and future Sprint work.

### Overview
There are a bevvy of comments available on Reddit (specific to [Benefits](https://www.reddit.com/r/VeteransBenefits/) and the [general Veteran populace](https://www.reddit.com/r/Veterans/)) that address the happiness of the desired audience (the Veterans) about the current MVP Mobile product. This is beneficial for the UX and Product teams, and in the future, the Engineering team, because we are able to see what people have to say in a real-time situation, and how they either remedy the issue as a community or how they are otherwise guided to fix their issues. 

## Tasks
- [x] Review [Veterans Benefits](https://www.reddit.com/r/VeteransBenefits/) for app-related issues
- [x] Review [Veterans](https://www.reddit.com/r/Veterans/) for app-related issues
- [x] Document the findings
- [ ] Review with UX team for future work planning

## Acceptance Criteria
- [ ] Documented findings from Reddit
- [ ] Plan for future work based on the documented finding
