### ISSUE TITLE
Discovery - Review social media apps for Flagship Mobile feedback that will inform future sprint work

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#68]
### User Story
As the Product and UX resources on the MFS team,
We need to review other social media sites to collect feedback about the Flagship Mobile App, 
So that we know how to plan our strategies, further research, and future Sprint work.

### Overview
After reviewing Reddit for feedback from end users and collecting that information, there are other social media sites that could be scraped for user feedback. By understanding and addressing the happiness of the desired audience (the Veterans) about the current MVP Mobile product, we can be more intentional about our priorities. This is beneficial for the UX and Product teams, and in the future, the Engineering team, because we are able to see what people have to say in a real-time situation, and how they either remedy the issue as a community or how they are otherwise guided to fix their issues. 

## Tasks
- [x] Review other social media sites for feedback on the Flagship Mobile app
- [x] Document the findings
- [x] Review with UX team for future work planning

## Acceptance Criteria
- [x] Documented findings from other social media sites
- [x] Prioritization of future work based on the documented finding
