### ISSUE TITLE
Design System Replacement - meeting with Flagship Mobile

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#79]
### User Story
As the Product, Engineering, Research and UX resources on the MFS team, 
We need to better understand the Design System Replacement current status by meeting with Flagship Mobile resources,
So that we can better understand what still needs to be implemented in the Mobile product.

### Overview
The Flagship Mobile team has updated the Mobile App with a few components of the Design System. We will meet with resources from Flagship Mobile to better understand what has been completed and what has yet to be implemented. 

## Tasks
- [x] Meet with Kelly from Flagship Mobile
- [x] Document meeting notes and outcomes
- [x] Ticket new work

## Acceptance Criteria
- [x] MFS team has a better understanding of what Design Systems components have been implemented, and what work is still to be done.
