### ISSUE TITLE
Engineering Technical Audit for Pre-Need Burial Service

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#81]
### User Story
As the Engineers on MFS, 
We need to perform a technical audit of the Flagship Mobile assets,
So that we understand the code and will be able to make improvements in the code.

### Overview
Engineering is performing a technical audit on the Flagship Mobile assets in order to understand the code in it's current state, how it's set up, and becoming aware of any anomalies that may need to be documented, before the MFS team can begin to design, develop and implement any new products. Pre-Need Burial is the first objective 

## Tasks
- [ ] Technical audit of Flagship Mobile assets
- [ ] Documentation as necessary

## Acceptance Criteria
- [ ] The MFS Engineering team will have insight to how the code is crafted in the current Flagship Mobile application.
