### ISSUE TITLE
Design System: Discovery on LOE to incorporate new Loading Component into the App

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#84]
## User Story
As a developer on the MFS team, 
We need to implement the new Loading Component into the current VA Flagship Mobile code
So that the Loading component behaves consistently across screens to the users.

## Overview
_(Taken from the Flagship Mobile _[ticket 8936](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8936))__ : 
### Project Objective:
The Design System team has built the new Loading component as part of department-of-veterans-affairs/va-mobile-library#71. This Epic covers the Flagship Global team implementing that new component in the Global sections of the app. The Flagship team will give feedback on the process to the Design System team to help them improve the Design System.
### Loading Component Notes
- The Sync screen is currently using a white variant of the LoadingIndicator which will not be available with the new version
- The app team has plans to redesign the login/sync screens with light/dark mode, so the LoadingIndicator should not be replaced on these screens until that work is complete
- If the app team would like to avoid linting warnings for this screen, they should delay updating the linting package to the latest version until all of the LoadingComponents have been replaced with LoadingIndicator

## Tasks
- [x] Assess the Loading Component work from the DS
- [x] Determine best implementation strategy and communicate with the Flagship Mobile team before making any changes to the code
- [x] Once the strategy is approved, implement code
- [x] Sent test/PR to Flagship Mobile team for QA
- [ ] Feedback, fixes
- [ ] Documentation

## Acceptance Criteria
- [ ] New Loading Component has been implemented, tested, and approved for review by Accessibility, then approved for release.
