### ISSUE TITLE
Design Systems: Update Semantic Color Tokens in the Flagship App Figma (Navigation)

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#85]
## User Story
As the UX team on the MFS team, 
We need to update the semantic color token navigation in the VA Mobile app,
So that the semantic color token navigation is current with the Design Systems requirements.

## Overview
_(Taken from the Flagship Mobile _ [ticket 8798]https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8798)__ : 
### Project Objective:
Project Objective:
The Design System team has built new Semantic Color tokens as part of department-of-veterans-affairs/va-mobile-library#78. This Epic covers the Flagship Global team implementing the new Semantic Color Tokens in the Global sections of the app. The Flagship team will give feedback on the process to the Design System team to help them improve the Design System.

**Suggested process**

**Step 1: Designer updates Figma with semantic tokens.**
1. In the Flagship Library, the designer updates the components with semantic tokens.
     - The DS team recommends splitting up the work by section (Alerts and progress, Buttons and links, etc.) and tackling the smallest components first. This will prevent any accidental overrides in the larger components.
     - Each section should be edited in its own branch.
          - Branch should be reviewed/approved by Jessica.
          - If an appropriate semantic token does not exist, notify the DS team and they will provide a recommendation or next step.
2. In the shipped files, the designer updates the components.
     - Each file should be edited in its own branch.
          - After updating the components, the designer should verify that there are no primitive tokens used in the shipped files.
          - If an appropriate semantic token does not exist, notify the DS team and they will provide a recommendation or next step.
          - Dark mode can then be removed from the shipped files.
          - Designer will ensure that color contrast meets minimum requirements in light/dark mode.
          - Branch should be reviewed/approved by Jessica.
3. Designer archives Foundations Library.
4. Designer removes Colors page from Flagship Library.

**Step 2: Engineer updates mobile app based on Figma mockups.**
- If a Figma mockup does not exist for a screen in the app, the engineer will need to consult with a designer.

**Step 3: Designer completes visual QA in the mobile app.**
- If there are issues with how the semantic tokens appear in light/dark mode in the app, reach out to UX.

## Tasks
- [ ] Review the suggested steps above for how to update the semantic colors. 
- [ ] Check color contrast for Navigation components in the Flagship library (pagination and carousel)
- [ ] Update Navigation components in the flagship library 
- [ ] @platform-design-system-designers is tagged on this ticket when the components are updated in the Flagship library for review
- [ ] If there are blockers to the work, document the blockers
- [ ] Documentation

## Acceptance Criteria
- [ ] Color tokens are applied to the pagination component
- [ ] Color tokens are applied to the carousel component
- [ ] Color tokens for Navigation (pagination and carousel components) are approved by the Design System team
