### ISSUE TITLE
Design Systems: Incorporate Icon Component into the Flagship App

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#86]
## User Story
As an Engineer on the MFS team, 
We need to incorporate the Icon Component in the Flagship App,
So that the Icon Components that display in the App are compliant with the Design Systems requirements.

## Overview
_(Taken from the Flagship Mobile _ [ticket [7695](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7695)]__ : 
### Project Objective:
Project Objective:
- The Design System team will be creating a new Icon component.  
- The Design System team recommends that all icons are replaced in the app around the same time. The icon component includes the new Material icons and have slight sizing differences from the old FontAwesome icons.
- During handoff, engineering needs to work with UX Design regarding the bottom tab bar icons. There may be tweaks we choose to make from a design perspective. For example: Currently, the door in the home screen icon changes size slightly. 

## Tasks
- [ ] Incorporate the Icon Component throughout the App
- [ ] If there are blockers to the work, document the blockers
- [ ] Documentation

## Acceptance Criteria
- [ ] The Icon Components have been implemented, tested, and approved for review by Accessibility, then approved for release.
