### ISSUE TITLE
Design Systems: Implement Spacing Tokens in VAHB App

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#88]
## User Story
As an Engineer on the MFS team, 
We need to implement spacing tokens in the Flagship App,
So that the spacing tokens that display in the App are compliant with the Design Systems requirements.

## Overview
_(Taken from the Flagship Mobile _ [ticket [9750](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9750)]__ : 
### Project Objective:
Project Objective:
- Incorporate the new Spacing tokens into the Flagship App
- See [Mobile DS docs](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Foundation/Design%20tokens/Spacing) for additional details

## Tasks
- [ ] Incorporate the spacing tokens throughout the App
- [ ] If there are blockers to the work, document the blockers
- [ ] Documentation

## Acceptance Criteria
- [ ] That the spacing tokens has been implemented, tested, and approved for review by Accessibility, then approved for release.
