### ISSUE TITLE
Accessibility Review Process

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#90]
##User Story:
As team leads and managers for the MFS team, 
We need to determine our Accessibility Review process and how it will work going forward, 
So that our releases are not delayed by Accessibility issues. 

##Overview
We need to understand the current Accessibility review process that the Flagship Mobile team is doing, so that continuity of releases will happen as MFS begins to release new code in the app and there are no issues or delays with accessibility. 

_This was taken from a [Flagship Mobile Accessibility Review ticket](https://github.com/department-of-veterans-affairs/va-mobile-library/issues/524)_
This is the Flagship Mobile team's checklist, and it is used during review whenever a new piece of code is ready to be released. Without proper accessibility reviews and approvals, the MFS team will be delayed from releasing new code. 
- Once the Checkbox Group component is available in Storybook, Brea (Flagship Mobile accessibility designer) will complete an accessibility review and create tickets for any additional work.

##Acceptance Criteria
- [ ] Review Checkbox component for and accessibility issues
- [ ] Review Checkbox Group component for and accessibility issues
- [ ] Create Bug tickets for any changes needed

##Accessibility Audit Checklist
- [ ] Verify that the component scales with increased font sizes and with display zoom enabled.
- [ ] Verify that the component passes color contrast minimums.
- [ ] Verify that no screenreader issues exist.
- [ ] Verify that the component works with a keyboard and that there are no keyboard traps.
- [ ] Verify that the component works with Voice Access / Switch Control.
- [ ] Verify that the overall structure is accessible (headings are properly labeled, etc.).
- [ ] Verify that any error messaging displays properly / as expected.
- [ ] Verify that any tappable areas (links, buttons, etc.) meet target size minimums.

##Tasks
- [ ] Review the current tools that Flagship Mobile is using
- [ ] Confirm whether or not MFS has the same tools 
- [ ] Procure whatever tools are outstanding, in order to provide continuity in the release
