### ISSUE TITLE
Pre-Need Burial SPIKE ticket - UX

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#91]
### User Story
As the UX and Research resources for the MFS team, 
We need to review the Pre-Need Burial information,
So that we can create a strategy for how best to implement a Pre-Need Burial claim for Veterans.

### Overview
Because the Pre-Need Burial claim is a priority for OCTO VAPO, it is necessary for the engineering team to better understand the current work that has been done to date. Review the links in the [Product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/PreNeed%20Burial%20Claim/PreNeedBurialClaim.md) for more insight to the research and findings that have been documented by Flagship Mobile. 
Pre-Need Sprint 0 ticket from Flagship Mobile is [here](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6116).
After @nhuckleberry6 and @emilyd-oddball have done this review, we will ticket the work. 

## Tasks
- [x] Review Flagship Mobile UX [ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6836) 
- [x] Review [Sprint 0 Discovery](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6116) 

## Acceptance Criteria
- [x] UX discovery is added to [our folder in Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/burials-memorials/pre-need/mobile) 
- [x] Any noteworthy lessons added to [lessons learned](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/burials-memorials/pre-need/mobile/lessons-learned.md)
