### ISSUE TITLE
Review current Mobile QA process

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#94]
##User Story:
As team leads and managers for the MFS team, 
We need to determine our QA process and how it will work going forward, 
So that our releases are not delayed by QA issues. 

##Overview
We need to understand the current QA review process that the Flagship Mobile team is doing, so that continuity of releases will happen as MFS begins to release new code in the app and there are no issues or delays with accessibility. 

##Acceptance Criteria
- [ ] TK

##Tasks
- [x] Review the current tools that Flagship Mobile is using
- [x] Confirm whether or not MFS has the same tools 
- [x] Procure whatever tools are outstanding, in order to provide continuity in the release
- [x] Create process for QA review
