### ISSUE TITLE
2024 Q4 Pre-Need Burial Claims: Research plan

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#97]
### User Story
As the UX and Research teams on MFS, 
We need to have a good understanding of Veterans' relationships to burial benefits
So that we can decide what elements of the pre-need burial benefit will be added to the mobile app.

### Overview
Currently eligible Veterans engaging with the VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) do not have a way to find, track and get statuses in the VA Flagship App. This means the Veterans can only go through Va.gov to access this information.

In June 2017, VA launched VA form-40-10007 (Application for Pre-need Determination of Eligibility for Burial in a VA National Cemetery) on Vets.gov. Vets.gov later transitioned to Va.Gov which currently enables Veterans to discover, apply for, track and manage this claim.

As of today, current focus has only been on maintaining this feature. 

Pre-need decision letter is not needed for a service member that is on active duty.

Pre-Needs Burial Claims are not currently in the claims status tool, only burial claims are in the claims too.

Specifically, we need to understand if the work outlined by Flagship Mobile back in 2023 is still viable and the most effective and efficient way to proceed.

We also need to pull back for a wider scope to find out if Veterans know about burial benefits, understand pre-need burial, and learn their goals with pre-need burial.

## Tasks
- [ ] Follow [Platform's research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist) for this ticket
- [ ] Draft a research plan that will address the objectives in #107 
- [ ] If any new research is unearthed, also review that
- [ ] Create a conversation guide
- [ ] Write screener questions
- [ ] Create timeline for research plan
- [ ] Discuss whether or not we want a kick-off call with Perigean

## Acceptance Criteria
- [ ] Flagship Mobile research has been validated, and the outstanding work can be ticketed for future Sprints. 
- [ ] The research plan exists on Github and follows [Platform's research plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md) 
- [ ] Screener questions are written for Perigean (reference [successful screener questions](https://depo-platform-documentation.scrollhelp.site/research-design/successful-screener-questions))
- [ ] The conversation guide exists on Github and follows [Platform's conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)
- [ ] If we want a kick-off call with Perigean, that is scheduled
