### ISSUE TITLE
Pre-Need Burial: Sitemap placement ideas

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#98]
### Problems to be solved
- How might we best surface pre-need burials in the app?
- How might we plan for additional forms within the app?

## Tasks
- [x] Explore ideas for the proper placement of pre-need burials in the mobile app on the sitemap
- [x] Create initial user flows for viewing pre-need burials in the app

## Acceptance Criteria
- [ ] Sitemap ideas have been shared with the team
- [x] Sitemap ideas have been shared with Ryan

## Out of Scope

- Further updates and approvals
