### ISSUE TITLE
Pre-Need Burial: Preliminary designs - View submission

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-feature-support#99]
### Problems to be solved
- **Replace with how might we questions**

## Tasks
- [x] User flows
- [x] Low-fi designs

## Acceptance Criteria
- [x] Create preliminary designs for viewing a Pre-Need Burial submission
- [x] Preliminary designs for viewing a Pre-Need Burial submission have been shared for feedback

## Related tickets

- https://github.com/department-of-veterans-affairs/va-mobile-feature-support/issues/218
